services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mikeb
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: optionsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_URI: postgresql://mikeb:postgres@db:5432/optionsdb
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: